snapcraft-version: 7.4.3
snapcraft-started-at: '2023-07-20T10:57:59.567179Z'
snapcraft-os-release-id: ubuntu
snapcraft-os-release-version-id: '22.04'
name: network-manager
version: 1.36.6-6
summary: Network Manager
description: |
  NetworkManager is a system network service that manages your network
  devices and connections, attempting to keep active network connectivity
  when available. It manages ethernet, WiFi, mobile broadband (WWAN) and
  PPPoE devices, provides VPN integration with a variety of different
  VPN services.
  Please find the source code for this track at:
    https://code.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/network-manager/+ref/snap-22
base: core22
grade: stable
confinement: strict
apps:
  nmcli:
    command: usr/bin/nmcli
    plugs:
    - nmcli
  nmtui:
    command: usr/bin/nmtui
    plugs:
    - nmcli
  nmtui-connect:
    command: usr/bin/nmtui-connect
    plugs:
    - nmcli
  nmtui-edit:
    command: usr/bin/nmtui-edit
    plugs:
    - nmcli
  nmtui-hostname:
    command: usr/bin/nmtui-hostname
    plugs:
    - nmcli
  networkmanager:
    command: bin/networkmanager
    daemon: simple
    slots:
    - service
    plugs:
    - modem-manager
    - ppp
    - network-setup-observe
    - wpa
    - firewall-control
    - hardware-observe
    - network-setup-control
    - login-session-observe
    - network-observe
    - network-control
parts:
  networkmanager-common:
    plugin: dump
    source: snap-common
    stage-packages: []
    stage: []
    prime: []
    build-packages: []
  changelog:
    plugin: nil
    override-build: 'cp "/build/ci-network-manager-vcbye0ls9q1hken8"/ChangeLog "$CRAFT_PART_INSTALL"/ChangeLog

      '
    organize:
      ChangeLog: snap/ChangeLog
    stage-packages: []
    stage: []
    prime: []
    build-packages: []
  stack-snaps-tools:
    plugin: nil
    source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/stack-snaps-tools
    source-type: git
    build-packages:
    - dpkg-dev
    - git
    stage-packages:
    - dnsmasq-base=2.86-1.1ubuntu0.3
    - libcurl3-gnutls=7.81.0-1ubuntu1.13
    - libjansson4=2.13.1-1.1build3
    - libldap-2.5-0=2.5.14+dfsg-0ubuntu0.22.04.2
    - libmm-glib0=1.20.0-1~ubuntu22.04.2
    - libndp0=1.8-0ubuntu3
    - libnewt0.52=0.52.21-5ubuntu2
    - libnghttp2-14=1.43.0-1build3
    - libnm0=1.36.6-0ubuntu2
    - libpsl5=0.21.0-1.2build2
    - librtmp1=2.4+20151223.gitfa8646d.1-2build4
    - libsasl2-2=2.1.27+dfsg2-3ubuntu1.2
    - libslang2=2.3.2-5build4
    - libteamdctl0=1.31-1build2
    - network-manager=1.36.6-0ubuntu2
    - pkexec=0.105-33
    - polkitd=0.105-33
    override-build: |
      set -ex
      find "$CRAFT_PART_INSTALL"/ -type f,l \
                -not -path "$CRAFT_PART_INSTALL"/'usr/share/doc/network-manager*' \
                -not -path "$CRAFT_PART_INSTALL"/'usr/share/doc/libnm0*' \
           -and -not -path "$CRAFT_PART_INSTALL"/'usr/share/doc/dnsmasq-base*' \
           -delete
      find "$CRAFT_PART_INSTALL"/ -type d -empty -delete
      mkdir -p "$CRAFT_PART_INSTALL"/build-tools
      cp build-tools/* "$CRAFT_PART_INSTALL"/build-tools
    prime:
    - usr/share/doc/network-manager/copyright
    - usr/share/doc/libnm0/copyright
    - usr/share/doc/dnsmasq-base/copyright
    - usr/share/doc/network-manager/changelog.*
    - usr/share/doc/libnm0/changelog.*
    - usr/share/doc/dnsmasq-base/changelog.*
    stage: []
  dnsmasq:
    after:
    - stack-snaps-tools
    plugin: make
    source: https://git.launchpad.net/ubuntu/+source/dnsmasq
    source-type: git
    source-branch: applied/ubuntu/jammy-updates
    build-packages:
    - build-essential
    make-parameters:
    - PREFIX=/
    override-build: |
      set -ex
      "/build/ci-network-manager-vcbye0ls9q1hken8/stage"/build-tools/check-versions dnsmasq-base no
      git apply "/build/ci-network-manager-vcbye0ls9q1hken8"/snap-patch/dnsmasq.patch
      craftctl default
    prime:
    - sbin/dnsmasq
    stage-packages: []
    stage: []
  networkmanager:
    after:
    - stack-snaps-tools
    plugin: autotools
    source: https://git.launchpad.net/ubuntu/+source/network-manager
    source-type: git
    source-branch: applied/ubuntu/jammy-updates
    build-packages:
    - intltool
    - libglib2.0-dev
    - ppp-dev
    - libgnutls28-dev
    - uuid-dev
    - systemd
    - libsystemd-dev
    - libudev-dev
    - libgirepository1.0-dev
    - gobject-introspection
    - python3-gi
    - libpsl-dev
    - libcurl4-gnutls-dev
    - libglib2.0-doc
    - libmm-glib-dev
    - libndp-dev
    - libreadline-dev
    - libnewt-dev
    - libteam-dev
    - libjansson-dev
    - libnss3-dev
    - dbus
    - python3-dbus
    - gtk-doc-tools
    - libnetplan-dev
    - netplan.io
    - libyaml-dev
    autotools-configure-parameters:
    - --prefix=/usr
    - --sysconfdir=/etc
    - --localstatedir=/var
    - --runstatedir=/run
    - --disable-qt
    - --with-dhcpcd=no
    - --with-dhclient=no
    - --with-dnsmasq=/snap/network-manager/current/sbin/dnsmasq
    - --with-iptables=/sbin/iptables
    - --with-systemd-journal=yes
    - --libexecdir=/snap/network-manager/current/usr/lib/NetworkManager
    - --with-pppd=/snap/network-manager/current/usr/sbin/pppd
    - --with-pppd-plugin-dir=/snap/network-manager/current/usr/lib/pppd/2.4.9/
    - --with-dnssec-trigger=/usr/lib/dnssec-trigger/dnssec-trigger-script
    - --with-systemdsystemunitdir=/lib/systemd/system
    - --with-udev-dir=/lib/udev
    - --with-crypto=gnutls
    - --with-session-tracking=no
    - --with-suspend-resume=systemd
    - --with-modem-manager-1
    - --with-nmtui=yes
    - --with-nmcli=yes
    - --with-selinux=no
    - --with-tests
    - --with-libaudit=no
    - --without-dhcpcanon
    - --disable-polkit
    - --disable-polkit-agent
    - --enable-ppp
    - --enable-ifupdown
    - --enable-introspection
    - --disable-gtk-doc
    - --enable-concheck
    - --enable-teamdctl
    - --enable-json-validation
    - --disable-more-warnings
    - --disable-modify-system
    - --disable-ovs
    - --without-nm-cloud-setup
    - CFLAGS=-O2
    override-build: |
      set -ex

      # Download VPN packages here, we cannot just stage as they pull
      # the NM package which will conflict with our build.
      apt download network-manager-openvpn
      dpkg -x network-manager-openvpn_*.deb "$CRAFT_PART_INSTALL"/

      "/build/ci-network-manager-vcbye0ls9q1hken8/stage"/build-tools/check-versions network-manager yes
      git config user.email "snapcraft@canonical.com"
      git config user.name "snapcraft"
      git am "/build/ci-network-manager-vcbye0ls9q1hken8"/snap-patch/networkmanager/*.patch

      # re-create configure
      ./autogen.sh
      craftctl default

      # Run all tests NetworkManager ships by default
      # Hide the $SNAP env variable during testing, to prevent the netplan CLI
      # from using the snap fallback io.netplan.Netplan.Generate() DBus API as
      # that does not allow to pass a --root-dir argument, needed for testing
      _SNAP=$SNAP
      unset SNAP
      make check
      SNAP=$_SNAP
      unset _SNAP
    stage-packages:
    - libbrotli1=1.0.9-2build6
    - libcurl3-gnutls=7.81.0-1ubuntu1.13
    - libjansson4=2.13.1-1.1build3
    - libldap-2.5-0=2.5.14+dfsg-0ubuntu0.22.04.2
    - libmm-glib0=1.20.0-1~ubuntu22.04.2
    - libndp0=1.8-0ubuntu3
    - libnewt0.52=0.52.21-5ubuntu2
    - libnghttp2-14=1.43.0-1build3
    - libpcap0.8=1.10.1-4build1
    - libpkcs11-helper1=1.28-1ubuntu0.22.04.1
    - libpsl5=0.21.0-1.2build2
    - librtmp1=2.4+20151223.gitfa8646d.1-2build4
    - libsasl2-2=2.1.27+dfsg2-3ubuntu1.2
    - libslang2=2.3.2-5build4
    - libteamdctl0=1.31-1build2
    - openvpn=2.5.5-1ubuntu3.1
    - ppp=2.4.9-1+1ubuntu3
    organize:
      snap/network-manager/current/usr/lib/pppd/2.4.9/nm-pppd-plugin.so: usr/lib/pppd/2.4.9/nm-pppd-plugin.so
      snap/network-manager/current/usr/lib/NetworkManager: usr/lib/NetworkManager
      usr/lib/x86_64-linux-gnu/NetworkManager: usr/lib/NetworkManager
    prime:
    - usr/bin/nmcli
    - usr/bin/nmtui
    - usr/bin/nmtui-connect
    - usr/bin/nmtui-edit
    - usr/bin/nmtui-hostname
    - usr/sbin/pppd
    - usr/lib/*/NetworkManager
    - usr/lib/pppd/2.4.9/nm-pppd-plugin.so
    - usr/lib/NetworkManager
    - usr/sbin/NetworkManager
    - usr/sbin/openvpn
    - etc/NetworkManager/*
    - usr/share/doc/libbrotli1/copyright
    - usr/share/doc/libcurl3-gnutls/copyright
    - usr/share/doc/libjansson4/copyright
    - usr/share/doc/libpkcs11-helper1/copyright
    - usr/share/doc/libldap-2.5-0/copyright
    - usr/share/doc/libmm-glib0/copyright
    - usr/share/doc/libndp0/copyright
    - usr/share/doc/libnewt0.52/copyright
    - usr/share/doc/libnghttp2-14/copyright
    - usr/share/doc/libpcap0.8/copyright
    - usr/share/doc/libpsl5/copyright
    - usr/share/doc/librtmp1/copyright
    - usr/share/doc/libsasl2-2/copyright
    - usr/share/doc/libslang2/copyright
    - usr/share/doc/libteamdctl0/copyright
    - usr/share/doc/openvpn/copyright
    - usr/share/doc/ppp/copyright
    - usr/share/doc/libbrotli1/changelog.*
    - usr/share/doc/libcurl3-gnutls/changelog.*
    - usr/share/doc/libjansson4/changelog.*
    - usr/share/doc/libpkcs11-helper1/changelog.*
    - usr/share/doc/libldap-2.5-0/changelog.*
    - usr/share/doc/libmm-glib0/changelog.*
    - usr/share/doc/libndp0/changelog.*
    - usr/share/doc/libnewt0.52/changelog.*
    - usr/share/doc/libnghttp2-14/changelog.*
    - usr/share/doc/libpcap0.8/changelog.*
    - usr/share/doc/libpsl5/changelog.*
    - usr/share/doc/librtmp1/changelog.*
    - usr/share/doc/libsasl2-2/changelog.*
    - usr/share/doc/libslang2/changelog.*
    - usr/share/doc/libteamdctl0/changelog.*
    - usr/share/doc/openvpn/changelog.*
    - usr/share/doc/ppp/changelog.*
    - usr/share/doc/network-manager-openvpn/changelog.*
    - usr/lib/*/libslang*
    - usr/lib/libnm*
    - usr/lib/*/libbrotli*
    - usr/lib/*/libcurl-gnutls*
    - usr/lib/*/libjansson*
    - usr/lib/*/libpkcs11-helper*
    - usr/lib/*/liblber-2.5*
    - usr/lib/*/libldap-2.5*
    - usr/lib/*/libmm-glib*
    - usr/lib/*/libnewt*
    - usr/lib/*/libndp*
    - usr/lib/*/libnghttp2*
    - usr/lib/*/libpcap*
    - usr/lib/*/libpsl*
    - usr/lib/*/librtmp*
    - usr/lib/*/libsasl2*
    - usr/lib/*/libteamdctl*
    - usr/lib/openvpn/*
    - usr/lib/*/openvpn/plugins/*
    - -usr/lib/NetworkManager/nm-dhcp-helper
    - -usr/lib/NetworkManager/1.36.4/libnm-device-plugin-adsl.so
    - -usr/lib/NetworkManager/1.36.4/libnm-device-plugin-bluetooth.so
    - -usr/lib/NetworkManager/*/*.la
    - -usr/lib/libnm.la
    - -usr/lib/pkgconfig
    stage: []
architectures:
- amd64
image-info:
  build_url: https://launchpad.net/~snappy-hwe-team/+snap/ci-network-manager-vcbye0ls9q1hken8/+build/2174855
build-packages: []
build-snaps: []
primed-stage-packages:
- dnsmasq-base=2.86-1.1ubuntu0.3
- libbrotli1=1.0.9-2build6
- libcurl3-gnutls=7.81.0-1ubuntu1.13
- libjansson4=2.13.1-1.1build3
- libldap-2.5-0=2.5.14+dfsg-0ubuntu0.22.04.2
- libmm-glib0=1.20.0-1~ubuntu22.04.2
- libndp0=1.8-0ubuntu3
- libnewt0.52=0.52.21-5ubuntu2
- libnghttp2-14=1.43.0-1build3
- libnm0=1.36.6-0ubuntu2
- libpcap0.8=1.10.1-4build1
- libpkcs11-helper1=1.28-1ubuntu0.22.04.1
- libpsl5=0.21.0-1.2build2
- librtmp1=2.4+20151223.gitfa8646d.1-2build4
- libsasl2-2=2.1.27+dfsg2-3ubuntu1.2
- libslang2=2.3.2-5build4
- libteamdctl0=1.31-1build2
- network-manager=1.36.6-0ubuntu2
- openvpn=2.5.5-1ubuntu3.1
- ppp=2.4.9-1+1ubuntu3
