name: Release snap

on:
  workflow_dispatch:
    branches:
      - snap-24

jobs:
  build_release:
    runs-on: self-hosted
    environment: beta
    steps:
      - name: Build release
        env:
          LP_CREDENTIALS: ${{ secrets.LP_CREDENTIALS }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        uses: snapcore/system-snaps-cicd-tools/action-release@main
        with:
          # TODO: remove this filter when snapd 2.64 is released
          architectures: arm64,amd64,armhf