name: Spread tests

on:
  push:
    branches:
      - snap-22-test
  pull_request:
    branches:
      - snap-22-test
      - snap-22

jobs:
  build:
    # Need to share self hosted runners with repo
    #runs-on: self-hosted
    runs-on: ubuntu-22.04
    steps:
      - name: Cleanup job workspace
        id: cleanup-job-workspace
        run: |
          printf "cleaning up\n"
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"
      - name: Checking out
        uses: actions/checkout@v3
      - name: Build snap
        env:
          LP_CREDS: ${{ secrets.LP_CREDS }}
        run: |
          set -exu
          printf "%s\n" "$LP_CREDS" > /tmp/.launchpad.credentials
          echo "Running spread"
          # We are inside of the checked out repo
          pwd
          id
          env
          #./cicd/workflows/snap-build.sh "${{ runner.temp }}"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: network-manager-snaps
          # TODO Set from metadata file (action.yaml)?
          path: ${{ runner.temp }}/network-manager_*.snap
      - name: Run spread tests
        run: |
          # TODO tests for other archs?
          mv "${{ runner.temp }}"/network-manager_*_amd64.snap .
          # curl -s https://storage.googleapis.com/snapd-spread-tests/spread/spread-amd64.tar.gz |
          #     tar -xz
          spread google:
      - name: Discard spread workers
        if: always()
        run: |
          shopt -s nullglob
          for r in .spread-reuse.*.yaml; do
              spread -discard -reuse-pid="$(echo "$r" | grep -o -E '[0-9]+')"
          done
